name: Deploy Kaleido Client
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    name: Build And Release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout kaleido-client
        uses: actions/checkout@v4
      - name: Get Version
        id: get_version
        if: matrix.os != 'windows-latest'
        run: |
          latestTag=${GITHUB_REF/refs\/tags\//}
          echo version is $latestTag
          echo "VERSION=$latestTag" >> "GITHUB_ENV"
      - name: Get latest tag
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $verSplit = $("${{ github.ref }}" -split "/")
          $ver=$verSplit[2]
          echo "latestTag is $ver"
          echo "VERSION=$ver" >> "$env:GITHUB_ENV"
      - name: show version 
        run: echo "version is ${{ env.VERSION }}"
      - name: show GITHUB_REF_NAME
        run: echo "version is $env:GITHUB_REF_NAME"
