name: Deploy Kaleido Client
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
        node_version:
          - '16.4.2'
          - '17'
          - '17'
        architecture:
          - x64
        include:
          - os: windows-2016
            node_version: '16.4.2'
            architecture: x86
    name: Build And Release
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Get Version for Windows
        if: matrix.os == 'windows-latest'
        id: get_version
        shell: pwsh
        run: |
          $githubRef = $env:GITHUB_REF
          $splitRef==$githubRef -split "/"
          $VER=$splitRef[2]
          echo "VERSION=$VER" >> "$GITHUB_OUTPUT"
      - name: show version
        run: |
          echo get version is  ${{steps.get_version.outputs.VERSION}}
      - name: Get Version2
        if: matrix.os != 'windows-latest'
        id: get_version2
        run: |
          VER=${GITHUB_REF##*/}
          echo "VERSION=$VER" >> "$GITHUB_OUTPUT"
      - name: show version2
        run: |
          echo get version2 is  ${{steps.get_version2.outputs.VERSION}}

   
  
