name: Deploy Kaleido Client
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    name: Build And Release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout kaleido-client
        uses: actions/checkout@v4
      - name: Show GITHUB_REF_NAME
        run: |
           echo "GITHUB_REF_NAME is ${{ matrix.os == 'windows-latest' && `$env:GITHUB_REF_NAME` || `$GITHUB_REF_NAME` }}
